apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: route-finder
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/p0dxD/main_configs.git
    targetRevision: main
    path: gitops/route-finder
  destination:
    server: https://kubernetes.default.svc
    namespace: route-finder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
