apiVersion: v1
kind: ConfigMap
metadata:
  name: graphhopper-config
  namespace: route-finder
data:
  config.yml: |
    graphhopper:
      datareader.file: /data/maryland_virginia_dc.osm.pbf
      graph.location: /data/gh-cache

      import.osm.ignored_highways: ''
      graph.encoded_values: car_access, road_environment, ferry_speed, car_average_speed, max_speed, foot_access, foot_average_speed, foot_priority, hike_rating, foot_road_access, mtb_rating

      profiles:
        - name: car
          custom_model_files: [car.json]
        - name: foot
          custom_model_files: [foot.json]

      # CH disabled so alternative_route algorithm works
      profiles_ch: []

      # Landmark-based speedup without CH
      profiles_lm:
        - profile: car
        - profile: foot

    server:
      application_connectors:
        - type: http
          port: 8989
          bind_host: 0.0.0.0
      admin_connectors:
        - type: http
          port: 8990
          bind_host: 0.0.0.0
      request_log:
        appenders: []
