---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: storage-configuration
  namespace: minio-tenant
spec:
  encryptedData:
    config.env: AgDC8uo/19PnjCaI71ZImwjdYpVWYI/7KsrfBXY1Be+F/7JOGbqloALfA4FRbVqBG97CMbNTZzixxnhTfxHi6rO7xm51pMy9zgagBHQi24vU2abv+G+b0Wkfm4CyuAqr/DpaxxadmU02fWpUz6GqbU/UNnPNcuvOA0+pDih7wx0q4FJe2Y2akomJxNmvdIyn6jandgZ+r5fzK0a8J0i82JA94ZhVTrKTlY5xYux7hz/AOzBoUwzJg1QjfCFwBJ5pNfzGbSdf/GFbgOOjmEDufCXXm+IBftMzlFtNI9Wf+xiZypDQkEKy7WSXH5dyd9XD8W6hbzEGQgVky/Gk7OH3jCilHaWEDgoOtAJJq8uiOQZp+40S//oi5S3RWDPNO72820drpL8kL2oZDm7EmMC1O8MR7oRB5mPU780lj7MCvE5wwGUTjfh6JuRPzwlKubLZzZzE/Mr6jwPwgRdeh3/Mc3HUgLh3ojwg0Wvc24qmeln+8RUV+Syoj5QJ0dfNS4Ii2nvfrtz2aR6PPRdYS2X9Ly8j6NI31PvKoIacooP3duHB5ryOrY1JRi9hH5yibB2fTP7lbvyvw6/CtZtjMFYX0vf5zusPHZWXtkir0f0xllKBSOCWn0V/wP4fcsfDJ0RZE3FuQq5zUhcm88/bdB6RgunbPG5X+fV9CkIn727UQDoWYOQ86fvmnSVfGqc6M+mY7ixvNdqaZnlhfjgvn30IZJrdTGVF3x7P1m2sYZSkB7lnlH0QyRlDh+WIH/BdCwaxix6Xv/mdMVvjaxxz2OB/iv3wioWWLX/WKi3msqM2Qm7MP+M0pECP2t6VoZ5iPJWNNRumpHv6mvHu1Eeq2QTN8otJQfO3fxnqSWcO7HC/IRXuVCw5QAiN6EDUurusF7YHt56yRbv0/lE9Y2TiRqkKBJsQoQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: storage-configuration
      namespace: minio-tenant
    type: Opaque
