---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: storage-configuration
  namespace: minio-tenant
spec:
  encryptedData:
    config.env: AgBLyWzY5Y3+gNQV9BTu5UNI0PPQQr6zApujiA/xZx1sZD7YCf6sIuq/aJJaukl/kOwMGyow+/zTLnpsGYenu+QUGMHVrVf0TWJI/gJfvKoVzm8O0g3cwrp0bGm8IUCOl7PDW+GoleNB5lEeT/aXzVSwPOOn7YcTP2KrFIsNOnkHWRLQCPe5GTOZXV2DbKvTWGPYPDaN1+aS4TqZ3acyhR3I9eWkNGymxc4ymqT0QIppVLbfYsIlxfx0Z58gEO67yzafz+9fQBFAAxIbySrWCcjb8m52qzvvdk1d1cGW4jSaLXt6oEc2TkX0n0HXHLUuHjkZem3pLlpdicZuxMssYTsHtl6F04H1jB/eWPobzMbxwzIxr19qUUtlVlHclkiqaF8HhOpwQjW3fFTOprkHSff0T0NcUIGknsAKLpbpbdfdpCXNsEQh7Gq6N6yIwH3Xajh1+k/htleR2r5pGCnQcHz6iIT0TOMvjBo3ZoNNDNmNZ3r1Q5GObUuAtg4ZYx/U2f20KgDCwMV4XfT8bIf2rX7Y0VappvmQSfN7biwkC5xGM9eX/khN7gPnInFxrdLmBScCCyRrsxgE8a7Bqqpv2rEzCOZDU299tOlLN9/miOpHrebZY+W4Q5Dep+vn1yRpVwo3lJSfwnEDiJ94eYjIaDRN/qsM4D+7LShuauNrXmPGcFuPKE0uArLqDxRY3hvDipmlyIx5WAnw2//lmDKq1pKoAm12pfFEQV9lcUXJlV/3wC48OmS0y4ik5pXV/5zLNpm19VnrVPTIwTURdn0Snlagt0mHF7tB/GOuWseO2eSWZymdRLxZjnxTOXmF9Gto+wu/VbaEG6UtESbmigozVHtIVhArR0eamZS3tbHYyc6OU8uvlHQC4epPPPvJRla4gmbWXW7w7IOXuC5lj0ewMgvubQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: storage-configuration
      namespace: minio-tenant
    type: Opaque
