---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: minio-root-secret
  namespace: minio-tenant
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAUFw91pSQZAkqIXEG2FlvIjFa58KcBP4nSdL4KKQ9vuycLMxggY97W/Zrs+TqXG2TBOANlBvPBidWHxoHPYa2j1kqQzH7VoEEGt6sun3hYrvb8WU8RG8BaMza44+q66Z+m9QQCU0PpoCJYrsaQDGtUNAtDHAkTvT0BksBozytk4rKWrws6R7ixIwl/xG3we4uHSqedbLKSLyW2PYePOzlQ1P24Uq68SE9rSpwaeeIIXJQb+Y4g4gMjYtqiQyX+UUJGNFlYhRt1glS8xsLXiBlAl6T8NzMN8zMU2DH85O46CPCbbLyh7Yn2yNSWCvBlJplGXe+QPnrUNk9ErSXSI8iQ1bg4/86e3cmpQ0nXw7I8TCxY9tmCZ/hFR3ZsdOe3YqcxsVVfYOjCO3lFZqDZaXMzEnerBEhk+Q7KC683VbzIqcTbp7vVEwhB5P7CkO+J6AOZQJXHtqbNAOuUf+ZJQACJ89dRlfPHL5gXkhMQK1RQQDwd7mPp8Be146Bu2325Lk8oyolOI9GRPTjDYPHKNAJsZOfFw265p9chuz8gr3Bk/9enlbK5Yj9bGVuR0PZMff2XbQY9nknj0Eivo1Rigg2L5J1DvZqhHLiFfBzhdZOYOfOaGDbJQP6g7m3R9oh+Fsgl8v2IiIBtT+M8VgxOZy7gu5WAoequ6vbuUELstXJ9RKmoFze9RhaCD/W3Os/ephtGGOMiP4XSpigBP5NcezmCYpvIQOefa5ESnGLQ1YujdA==
    MINIO_ROOT_USER: AgBwSOIRh5mi/FI89pZK5rpwXdwIiWWNIkeX6Xdwo48iKoSdPtFy/6wN6OB8BokSEXgBT61FehQz9s2zE/FYZAG7Ty6JR/LinXJWAw2W4uTz3fmJLBWyhU4PO6o4HeuX28//M3K6LuBZFqMwmyQKV0tRUpL1BCXm8tedeB9kJcMqrh6ZU89qS6lKqv9f2P1Xm92ikXlqPO2odkQLRfRJyzyxYX3gtI8/HUdmf3gS1ynyedEv3KrEcIBNyUjFd4LxepSXz8nstE37Y5SyDDog/b6QHJDP3jSmvkxx0cYkxJj26lyKQYgzulJzRcdfLzZQGlfuH1RF2HDjCKcpK8BDMyiuNd2G/9ITYiVpxoLgrWe1PQW8G0yfOA2fq5Vmiko1NEXfEUyrUGkhsU1K8T8w9WK69d7ZNSSoccNhTwVBMN3FFvqlAPZspZxZIdDchUwTh3qWsw9OnAasBzlFFUocLdMGi5Gvy6u5Dl14oll/vmyOE3P4/Q2ijXSrk4ZkhMi5fdnWXXqkqmi6LwGkjgbrZbPOYJ3H4St9s4vQE8mbynLtA5EfIP1wEajWglhK0ZNCr3Ao0KU5zNkn/wps2d8+zmQQT5ENGRriBu4ptcUhg2b7Csgy+PnT+CTuyysWMd9zRYuHKQLCvhQNgjrXfNKv39t2fGQsjHxc9w7okUgEsbL/woQkByY5DCr/Nq4zTZD4SOfFnKopt1pHhl+Hag==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: minio-root-secret
      namespace: minio-tenant
    type: Opaque
